/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Groe
 */
public class Notifications extends javax.swing.JFrame {

    /**
     * Creates new form Notifications
     */
    public Notifications() {
        initComponents();
    }
    public Notifications(String Notifications, String Reservations) {
        initComponents();
        NotificationsDisplay.setText(Notifications);
        ReservationsDisplay.setText(Reservations);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReservationsDisplayPane = new javax.swing.JScrollPane();
        ReservationsDisplay = new javax.swing.JTextArea();
        NotificationsDisplayPane = new javax.swing.JScrollPane();
        NotificationsDisplay = new javax.swing.JTextArea();
        ReservationsIndicatorPane = new javax.swing.JScrollPane();
        ReservationsIndicator = new javax.swing.JTextArea();
        NotificationsIndicatorPane = new javax.swing.JScrollPane();
        NotificationsIndicatorArea = new javax.swing.JTextArea();
        CloseWindow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ReservationsDisplay.setEditable(false);
        ReservationsDisplay.setColumns(16);
        ReservationsDisplay.setRows(5);
        ReservationsDisplayPane.setViewportView(ReservationsDisplay);

        NotificationsDisplay.setEditable(false);
        NotificationsDisplay.setColumns(20);
        NotificationsDisplay.setRows(5);
        NotificationsDisplayPane.setViewportView(NotificationsDisplay);

        ReservationsIndicator.setEditable(false);
        ReservationsIndicator.setColumns(16);
        ReservationsIndicator.setRows(5);
        ReservationsIndicator.setText("\n\n             Reservations");
        ReservationsIndicatorPane.setViewportView(ReservationsIndicator);

        NotificationsIndicatorArea.setEditable(false);
        NotificationsIndicatorArea.setColumns(20);
        NotificationsIndicatorArea.setRows(5);
        NotificationsIndicatorArea.setText("\n\n                               Notifications");
        NotificationsIndicatorPane.setViewportView(NotificationsIndicatorArea);

        CloseWindow.setText("Close");
        CloseWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReservationsIndicatorPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReservationsDisplayPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NotificationsDisplayPane, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(NotificationsIndicatorPane))
                .addGap(26, 26, 26)
                .addComponent(CloseWindow)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReservationsIndicatorPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotificationsIndicatorPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CloseWindow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReservationsDisplayPane, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(NotificationsDisplayPane))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseWindowActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CloseWindowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notifications().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseWindow;
    private javax.swing.JTextArea NotificationsDisplay;
    private javax.swing.JScrollPane NotificationsDisplayPane;
    private javax.swing.JTextArea NotificationsIndicatorArea;
    private javax.swing.JScrollPane NotificationsIndicatorPane;
    private javax.swing.JTextArea ReservationsDisplay;
    private javax.swing.JScrollPane ReservationsDisplayPane;
    private javax.swing.JTextArea ReservationsIndicator;
    private javax.swing.JScrollPane ReservationsIndicatorPane;
    // End of variables declaration//GEN-END:variables
}
